spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ddd
    password: kiseok
    username: kiseok
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org.hibernate.SQL: debug

logging:
  level:
    ROOT: INFO
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm: TRACE
    org.springframework.transaction: TRACE
    com.mysql.cj.jdbc: TRACE